apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-gpu-monitor
  namespace: k8s-monitoring
  labels:
    app: k8s-gpu-monitor
    component: gpu-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-gpu-monitor
  template:
    metadata:
      labels:
        app: k8s-gpu-monitor
    spec:
      serviceAccountName: gpu-monitor
      containers:
      - name: gpu-monitor
        image: k8s-gpu-monitor:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: management
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,gpu-management"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: gpu-db-secret
              key: host
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: gpu-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gpu-db-secret
              key: password
        - name: CLUSTER_NAME
          value: "production-cluster"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /var/log/k8s-monitor
      volumes:
      - name: config
        configMap:
          name: gpu-monitor-config
      - name: logs
        emptyDir: {}