apiVersion: v1
kind: Service
metadata:
  name: k8s-gpu-monitor
  namespace: k8s-monitoring
  labels:
    app: k8s-gpu-monitor
spec:
  selector:
    app: k8s-gpu-monitor
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: management
    port: 8081
    targetPort: 8081